### ISSUE TITLE
Doesn't Support Auto Discovered

### ISSUE THREAD

**Issue by zymawy** [bpocallaghan/titan#2]
Nice Package Very Helpful, 
I noticed The Package Not Supporting Auto Discover. And The Command 
`λ php artisan titan:publish` Throwing Error 

`There are no commands defined in the "titan" namespace.`
Any Updates Soon?

**Comment by bpocallaghan** [comment]
Hi @zymawy 
Thanks for your interest in the project.
Sorry, I was hospitalized for a few days and took some extra days off to recover.

To give you an overview:
Currently this is the [main project](https://github.com/bpocallaghan/laravel-admin-starter)
The project already uses some personal packages (alert, notify, generators, etc)
This 'titan' repository was at first just some files / classes / helpers (it actually started before I created the starter project)
So finally after some iterations I decided to move the 'core' functionality out of the starter project into this repository (and later move them into their own packages where needed)
As you can see I started with the easiest first (database). Hopefully I can add the controllers and assets soon so that I can update the main project and then do more updates faster.

I hope that explains it, please feel free to contribute if you want or give some ideas.

Not really sure when I will be able to update it, hope it will be soon tho :)
Have a lovely day!

**Comment by zymawy** [comment]
Keep The Hard Work Up @bpocallaghan 👍 🥇
